version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  # - package-ecosystem: npm
  #   directory: /deployment
  #   schedule:
  #     interval: daily

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
