// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/dragonfish/go/v2/pkg/logger"
	"github.com/ride-app/catalog-service/config"
	"github.com/ride-app/catalog-service/internal/api-handlers"
	"github.com/ride-app/catalog-service/internal/repositories/maps"
	"github.com/ride-app/catalog-service/third-party"
)

// Injectors from wire.go:

func InitializeService(logger2 logger.Logger, config2 *config.Config) (*apihandlers.CatalogServiceServer, error) {
	client, err := thirdparty.NewPlacesClient(logger2, config2)
	if err != nil {
		return nil, err
	}
	impl, err := maps.New(logger2, config2, client)
	if err != nil {
		return nil, err
	}
	catalogServiceServer := apihandlers.New(logger2, impl)
	return catalogServiceServer, nil
}
