// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/ride-app/entity-service/api/service"
	"github.com/ride-app/entity-service/config"
	"github.com/ride-app/entity-service/repositories/entity"
	"github.com/ride-app/entity-service/utils/logger"
)

// Injectors from wire.go:

func InitializeService(logger2 logger.Logger, config2 *config.Config) (*service.EntityServiceServer, error) {
	someImpl, err := entityrepository.NewSomeEntityRepository()
	if err != nil {
		return nil, err
	}
	entityServiceServer := service.New(someImpl)
	return entityServiceServer, nil
}
